export const COUNTRY_OPTIONS = [
  "Algeria",
  "Bahrain",
  "Egypt",
  "Iraq",
  "Jordan",
  "Kuwait",
  "Lebanon",
  "Libya",
  "Morocco",
  "Oman",
  "Palestine",
  "Qatar",
  "Saudi Arabia",
  "Sudan",
  "Syria",
  "Tunisia",
  "United Arab Emirates",
  "Yemen",
] as const;

/** Maps stored English country names to their i18n translation key (under the "countries" namespace). */
export const COUNTRY_KEY_MAP: Record<string, string> = {
  Algeria: "algeria",
  Bahrain: "bahrain",
  Egypt: "egypt",
  Iraq: "iraq",
  Jordan: "jordan",
  Kuwait: "kuwait",
  Lebanon: "lebanon",
  Libya: "libya",
  Morocco: "morocco",
  Oman: "oman",
  Palestine: "palestine",
  Qatar: "qatar",
  "Saudi Arabia": "saudiArabia",
  Sudan: "sudan",
  Syria: "syria",
  Tunisia: "tunisia",
  "United Arab Emirates": "uae",
  Yemen: "yemen",
};
