// Single source of truth for game genres. Stored in DB as the English value.
// i18n keys live under the `genres` namespace and are resolved via GENRE_I18N_KEYS.
export const GENRE_VALUES = [
  "Action",
  "Adventure",
  "Arcade",
  "Card / Board Game",
  "Casual",
  "Educational",
  "Endless Runner",
  "Family",
  "Fighting",
  "Horror",
  "Idle / Clicker",
  "Made for Kids",
  "Platformer",
  "Puzzle",
  "Racing",
  "Resource Management",
  "Rogue-lite",
  "Roguelike",
  "RPG",
  "Shooter FPS",
  "Simulation",
  "Sports",
  "Strategy",
  "Tower Defense",
  "Visual Novel",
] as const;

export type GenreValue = (typeof GENRE_VALUES)[number];

export const GENRE_I18N_KEYS: Record<string, string> = {
  "Action": "action",
  "Adventure": "adventure",
  "Arcade": "arcade",
  "Card / Board Game": "cardBoardGame",
  "Casual": "casual",
  "Educational": "educational",
  "Endless Runner": "endlessRunner",
  "Family": "family",
  "Fighting": "fighting",
  "Horror": "horror",
  "Idle / Clicker": "idleClicker",
  "Made for Kids": "madeForKids",
  "Platformer": "platformer",
  "Puzzle": "puzzle",
  "Racing": "racing",
  "Resource Management": "resourceManagement",
  "Rogue-lite": "rogueLite",
  "Roguelike": "roguelike",
  "RPG": "rpg",
  "Shooter FPS": "shooterFPS",
  "Simulation": "simulation",
  "Sports": "sports",
  "Strategy": "strategy",
  "Tower Defense": "towerDefense",
  "Visual Novel": "visualNovel",
};
